// Object of Codeforces tags with meaningful keys
const CODEFORCES_TAGS = {
  twoSat: "2-sat",
  binarySearch: "binary search",
  bitmasks: "bitmasks",
  bruteForce: "brute force",
  chineseRemainderTheorem: "chinese remainder theorem",
  combinatorics: "combinatorics",
  constructiveAlgorithms: "constructive algorithms",
  dataStructures: "data structures",
  dfs: "dfs and similar",
  divideAndConquer: "divide and conquer",
  dp: "dp",
  dsu: "dsu",
  expressionParsing: "expression parsing",
  fft: "fft",
  flows: "flows",
  games: "games",
  geometry: "geometry",
  graphMatchings: "graph matchings",
  graphs: "graphs",
  greedy: "greedy",
  hashing: "hashing",
  implementation: "implementation",
  interactive: "interactive",
  math: "math",
  matrices: "matrices",
  meetInTheMiddle: "meet-in-the-middle",
  numberTheory: "number theory",
  probabilities: "probabilities",
  schedules: "schedules",
  shortestPaths: "shortest paths",
  sortings: "sortings",
  stringSuffixStructures: "string suffix structures",
  strings: "strings",
  ternarySearch: "ternary search",
  trees: "trees",
  twoPointers: "two pointers",
};

// Export the tags object
module.exports.CODEFORCES_TAGS = CODEFORCES_TAGS;
